#!/usr/bin/python
import shutil
import subprocess

from setup_common import launchd_plist


masterdir = 'master'


with launchd_plist(masterdir):
    subprocess.check_call([
        '/usr/local/bin/buildbot',
        'create-master',
        '--relocatable',
        masterdir,
        ])
    
    for filename in ('master.cfg', 'master_config.py', 'passwords.py'):
        shutil.copy(filename, masterdir)
