#!/usr/bin/python
import os
import pwd
import socket
import subprocess
import sys

import master_config
from passwords import slave_pass
from setup_common import launchd_plist


slavename = sys.argv[1]
slavedir = 'slave'

master_hostname = master_config.hostname
if master_hostname == socket.getfqdn():
    master_hostname = 'localhost'


with launchd_plist(slavedir):
    subprocess.check_call([
        '/usr/local/bin/buildslave',
        'create-slave',
        '--relocatable',
        '--umask=022',
        slavedir,
        '%s:%d' % (master_hostname, master_config.slave_port),
        slavename,
        slave_pass[slavename],
        ])

    with open(os.path.join(slavedir, 'info/admin'), 'w') as fp:
        # Write current user's full name
        fp.write(pwd.getpwuid(os.getuid())[4] + '\n')

    with open(os.path.join(slavedir, 'info/host'), 'w') as fp:
        fp.write(subprocess.check_output([
            '/usr/sbin/system_profiler',
            '-detailLevel', 'mini',
            'SPHardwareDataType',
            ]))
